# Generated by Django 4.2.29 on 2026-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
