# Generated by Django 4.2.24 on 2026-04-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='File attachments metadata', null=True),
        ),
    ]
