# Generated by Django 4.2.29 on 2026-04-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='notebook_files',
            field=models.JSONField(blank=True, default=list, help_text='URLs and files loaded into Notebook LLM for this conversation', null=True),
        ),
    ]
