# Generated by Django 4.2.29 on 2026-04-11 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_conversation_notebook_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Presentation', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('modern', 'Modern Dark'), ('light', 'Clean Light'), ('gradient', 'Gradient Pop'), ('minimal', 'Minimal White'), ('corporate', 'Corporate Blue'), ('creative', 'Creative Purple')], default='modern', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('aspect_ratio', models.CharField(choices=[('16:9', '16:9 Widescreen'), ('4:3', '4:3 Standard'), ('21:9', '21:9 Ultrawide')], default='16:9', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('business', 'Business'), ('education', 'Education'), ('creative', 'Creative'), ('tech', 'Technology'), ('minimal', 'Minimal')], default='business', max_length=20)),
                ('layout', models.CharField(choices=[('title', 'Title Slide'), ('content', 'Content'), ('two-column', 'Two Column'), ('image-text', 'Image + Text'), ('text-image', 'Text + Image'), ('full-image', 'Full Image'), ('quote', 'Quote'), ('data', 'Data/Chart'), ('section', 'Section Divider'), ('blank', 'Blank')], max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='slide_templates/')),
                ('content', models.JSONField(default=dict)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SlideExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pptx', 'PowerPoint'), ('pdf', 'PDF'), ('html', 'HTML'), ('images', 'Image Sequence')], max_length=10)),
                ('file', models.FileField(upload_to='slide_exports/')),
                ('file_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='chat.slidedeck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('layout', models.CharField(choices=[('title', 'Title Slide'), ('content', 'Content'), ('two-column', 'Two Column'), ('image-text', 'Image + Text'), ('text-image', 'Text + Image'), ('full-image', 'Full Image'), ('quote', 'Quote'), ('data', 'Data/Chart'), ('section', 'Section Divider'), ('blank', 'Blank')], default='content', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='chat.slidedeck')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
