# Generated by Django 4.2.24 on 2026-04-19 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_slidedeck_slidetemplate_slideexport_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pro', models.BooleanField(default=False, help_text='User has active Pro subscription')),
                ('pro_expiry_date', models.DateTimeField(blank=True, help_text='Pro subscription expiry date', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
