# Generated by Django 4.2.24 on 2026-04-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_conversation_title_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlideTemplate',
        ),
    ]
